nameOverride: finddive-api
replicaCount: 2
# imagePullSecrets:
#   name: gcr-credential
image:
  repository: gcr.io/xx/xx
  tag: build-xxx
  pullPolicy: Always
containerPorts:
  - 4000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  # limits:
  #   cpu: 1100m
  #   memory: 1Gi
type: ClusterIP
default:
  ports:
    - name: http-api
      externalPort: 80
      internalPort: 4000
      protocol: TCP
healthCheck:
  port: 4000
  path: /

podAntiAffinity: true

envFrom:
    envFrom:
    - configMapRef:
        name: app-configmap
    - secretRef:
        name: app-secret